Add SegWit support
UNOMP/node-merged-pool pull request #4
Opened 2016-12-11 09:05 UTC by jameshilliard

This is an initial attempt at adding SegWit support, it appears to mine valid blocks on testnet.
I mined these two blocks which contain SegWit transactions:
https://www.blocktrail.com/tBTC/block/0000000000001117c46477e777a76c77857187d97aca5d0f621b29ed7dd45625
https://www.blocktrail.com/tBTC/block/00000000000017db788821b7e36f89c670b14888c3a946d8efdc72963115d755

2016-12-11 22:17 UTC, ahmedbodi commented
NACK! This is going to break POS coin support. There needs to be a config option which specifies something like segWitEnabled: true. if so then use this code, otherwise the old stuff

2016-12-11 22:22 UTC, jameshilliard commented
@ahmedbodi how would this affect POS coins? the witness commitment does not get inserted unless the node specifically requests it in the GBT response

2016-12-11 22:28 UTC, ahmedbodi commented
the GBT call, Old POS coins (even new ones really) expect the gbt call to pass nothing as params. This passes the whole rules and other stuff

2016-12-11 22:28 UTC, jameshilliard commented on lib/transactions.js
> +    if (rpcData.default_witness_commitment !== undefined){
If there is no "default_witness_commitment" in the GBT response the witness commitment is not inserted.

2016-12-11 22:31 UTC, jameshilliard commented
@ahmedbodi what about "capabilities"?

2016-12-11 22:32 UTC, jameshilliard commented on lib/pool.js
> -            [{"capabilities": [ "coinbasetxn", "workid", "coinbase/append" ]}],
Wouldn't this cause an issue for POS coins as well then?

2016-12-11 22:32 UTC, ahmedbodi requested changes

2016-12-11 22:32 UTC, ahmedbodi commented on lib/pool.js
> +                function(results){
Here, this would break POS coins. they expect to get [] not any content

2016-12-11 23:32 UTC, jameshilliard commented on lib/pool.js
> +                function(results){
It should now only send the params for POW coins

2016-12-12 10:24 UTC, ahmedbodi approved these changes
Untested. But Looks OK

2016-12-12 10:24 UTC, ahmedbodi commented on lib/pool.js
> -            [{"capabilities": [ "coinbasetxn", "workid", "coinbase/append" ]}],
weird. it certainly should do, i wonder when it was last changed

2017-02-10 14:02 UTC, btcdrak commented
@jameshilliard Please rebase.

This patch is working on mainnet, the following blocks were mined using this PR

http://explorer.litecoin.net/block/92f1efabbac74a0362a900aaf85b9419b8ef7daa2f7a347d5b917caf402a5ac7
http://explorer.litecoin.net/block/e2ce3731d61cc4c918fb76a1f46755a3ea05298e93f69b80ac96b85e03be04a4

2017-02-10 18:33 UTC, jameshilliard commented
rebased

2017-02-10 20:11 UTC, merged

2017-02-10 20:13 UTC, Infernoman commented
Going to make a slight change to this, cleaning up the second getblocktemplate for peercoin, and segwit. keep an eye out on the next commit.

2017-02-10 20:19 UTC, Infernoman commented
https://github.com/UNOMP/node-merged-pool/commit/c79e829d151fc90dfb2cff0399b995d76e2ce036

2017-04-07 20:27 UTC, jstefanop commented
@Infernoman Just to confirm, this patch will signal segwit blocks if I mine them? Thinking about setting up a pool to help Litecoin activate segwit. Any issues with merge mining segwit blocks with other coins?